// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSRE130veJpYdu_bkst7GWxDIX-yMcCso',
    appId: '1:140873861355:web:7e43cd9e5402d981cb16ae',
    messagingSenderId: '140873861355',
    projectId: 'koba-8ed9e',
    authDomain: 'koba-8ed9e.firebaseapp.com',
    storageBucket: 'koba-8ed9e.appspot.com',
    measurementId: 'G-6XQHQ535LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz4n-yKKgHB6h0mKStJWhNVjWI4PBuVIQ',
    appId: '1:140873861355:android:f9d2865d759f5f82cb16ae',
    messagingSenderId: '140873861355',
    projectId: 'koba-8ed9e',
    storageBucket: 'koba-8ed9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD3h08qYlbwZPbCjuo4Fn9ufd97M8hB2w',
    appId: '1:140873861355:ios:3ec9ad6a321fbc90cb16ae',
    messagingSenderId: '140873861355',
    projectId: 'koba-8ed9e',
    storageBucket: 'koba-8ed9e.appspot.com',
    iosBundleId: 'com.example.davesCakes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD3h08qYlbwZPbCjuo4Fn9ufd97M8hB2w',
    appId: '1:140873861355:ios:645d02b1b0c55c71cb16ae',
    messagingSenderId: '140873861355',
    projectId: 'koba-8ed9e',
    storageBucket: 'koba-8ed9e.appspot.com',
    iosBundleId: 'com.example.davesCakes.RunnerTests',
  );
}
